### ISSUE TITLE
Unable to run_low_mem( ),  VideoSys/examples/cogvideox /sample.py in T4 Colab 

### ISSUE THREAD

**Issue by sudhir2016** [NUS-HPC-AI-Lab/VideoSys#192]
Getting OOM error. Please help.

---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
[<ipython-input-2-b9b1556548fc>](https://localhost:8080/#) in <cell line: 2>()
      1 config = CogVideoXConfig("THUDM/CogVideoX-2b", cpu_offload=True, vae_tiling=True)
----> 2 engine = VideoSysEngine(config)
      3 prompt = "Sunset over the sea."
      4 video = engine.generate(prompt).video[0]

13 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in convert(t)
   1148                 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1149                             non_blocking, memory_format=convert_to_format)
-> 1150             return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
   1151 
   1152         return self._apply(convert)

OutOfMemoryError: CUDA out of memory. Tried to allocate 30.00 MiB. GPU 0 has a total capacity of 14.75 GiB of which 7.06 MiB is free. Process 16497 has 14.74 GiB memory in use. Of the allocated memory 14.19 GiB is allocated by PyTorch, and 456.84 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by oahzxl** [comment]
fixed in pr #194. it should work with t4 now.

if you still go oom. you can change the vae tiling args to use less memory here:
https://github.com/NUS-HPC-AI-Lab/VideoSys/blob/94e54cd4aadd35b817b37aed637a702a15786916/videosys/pipelines/cogvideox/pipeline_cogvideox.py#L174

an example is:
```
vae.enable_tiling(tile_sample_min_height=vae.tile_sample_min_height // 2)
```

**Comment by sudhir2016** [comment]
Thanks for your support. I used this
vae.enable_tiling(tile_sample_min_height=vae.tile_sample_min_height // 2)

But I am still getting oom. But now it says ' You session crashed after using all available RAM'. So now the oom is on RAM instead of VRAM.

**Comment by sudhir2016** [comment]
Ok thanks.
